### ISSUE TITLE
Try not to use really specific CSS selectors

### ISSUE THREAD

**Issue by oliverjam** [fac25/week2-markup-Suraj-Yassien#25]
https://github.com/fac25/week2-markup-Suraj-Yassien/blob/5ff7f72c06eee791d56d5b7284d047859ff54656/style.css#L158-L160

This CSS selector is very coupled to your DOM structure—if the way those elements is laid out in any way changes the styles will disappear. Also selectors like this have a higher "specificity", which makes it harder to override the CSS should you need to.

Lots more info:
- [Selector intent](https://cssguidelin.es/#selector-intent)
- [Location independence](https://cssguidelin.es/#location-independence)
- [Specificity](https://cssguidelin.es/#specificity)

Generally it's easier and safer to just use a single class to style things like this, or the least amount of nesting you can get away with. E.g.

```css
.subnav-link {
  padding: 8px 14px;
}
/* or maybe just */
ul ul a {
  padding: 8px 14px;
}
```
